apiVersion: v1
kind: Service
metadata:
  name: docker-react-node-port
spec:
  ports:
  - nodePort: 31515
    port: 3050
    targetPort: 3000
  selector:
    component: docker-react
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: web
  name: docker-react
spec:
  containers:
  - image: mempraqma/docker-react:latest
    name: client
    ports:
    - containerPort: 3000
